
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'unified_rag'
version: '0.0.1'

vars:
  unified_rag:
    ## Zendesk Sources
    zendesk_ticket: "{{ source('rag_zendesk', 'ticket') }}"
    zendesk_ticket_comment: "{{ source('rag_zendesk', 'ticket_comment') }}"
    zendesk_user: "{{ source('rag_zendesk', 'user') }}"

    ## Jira Sources
    jira_issue: "{{ source('rag_jira', 'issue') }}"
    jira_comment: "{{ source('rag_jira', 'comment') }}"
    jira_user: "{{ source('rag_jira', 'user') }}"
    jira_status: "{{ source('rag_jira', 'status') }}"
    jira_priority: "{{ source('rag_jira', 'priority') }}"

    # Hubspot Sources
    hubspot_engagement_note: "{{ source('rag_hubspot', 'engagement_note') }}"
    hubspot_engagement_email: "{{ source('rag_hubspot', 'engagement_email') }}"
    hubspot_engagement_company: "{{ source('rag_hubspot', 'engagement_company') }}"
    hubspot_engagement_contact: "{{ source('rag_hubspot', 'engagement_contact') }}"
    hubspot_engagement_deal: "{{ source('rag_hubspot', 'engagement_deal') }}"
    hubspot_company: "{{ source('rag_hubspot', 'company') }}"
    hubspot_contact: "{{ source('rag_hubspot', 'contact') }}"
    hubspot_deal: "{{ source('rag_hubspot', 'deal') }}"
    hubspot_owner: "{{ source('rag_hubspot', 'owner') }}"
    
models:
  unified_rag:
    intermediate:
      +materialized: ephemeral
    staging:
      +materialized: view
