
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'unified_rag'
version: '0.0.1'

vars:
  unified_rag:
    ## Zendesk Sources
    zendesk_ticket: "{{ source('rag_zendesk', 'ticket') }}"
    zendesk_ticket_comment: "{{ source('rag_zendesk', 'ticket_comment') }}"
    zendesk_user: "{{ source('rag_zendesk', 'user') }}"

    ## Jira Sources
    jira_issue: "{{ source('rag_jira', 'issue') }}"
    jira_comment: "{{ source('rag_jira', 'comment') }}"
    jira_user: "{{ source('rag_jira', 'user') }}"
    jira_status: "{{ source('rag_jira', 'status') }}"
    jira_priority: "{{ source('rag_jira', 'priority') }}"